# Generated by Django 2.2 on 2021-01-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=18)),
                ('loopback', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=14)),
                ('mac_address', models.CharField(max_length=17)),
            ],
            options={
                'db_table': 'router_details',
                'unique_together': {('loopback', 'hostname')},
            },
        ),
    ]
