# Generated by Django 2.2 on 2021-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerdetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
