# Generated by Django 2.2 on 2021-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_routerdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetails',
            name='hostname',
            field=models.CharField(max_length=15),
        ),
    ]
